### ISSUE TITLE
`generate_location` just works for the `store` storage.

### ISSUE THREAD

**Issue by johnunclesam** [shrinerb/shrine#275]
In the below example the `generate_location` just works for the `store` storage and not the `cache` one.

**Why?**

```ruby
class FileUploader < Shrine
  def generate_location(io, context)
    "student_profile/#{super}"
  end
end
```

**Comment by janko-m** [comment]
When the file is uploaded via the uploader, `#generate_location` is called regardless of what the storage is.

Maybe you're doing direct uploads to S3, in which case it won't be called because the file is not actually being uploaded through the uploader, it's uploaded on the client side directly to the storage. In the `presign_endpoint` you can modify the upload location via the `:presign_location` option, which receives a proc that is called with the request object, so you can make it conditional depending on the query parameters.
