### ISSUE TITLE
Can't retrieving original file name in file.download

### ISSUE THREAD

**Issue by surajit** [shrinerb/shrine#284]
I've added this code in initializers/shrine.rb (Rails app)

```rb
Shrine.plugin :presign_endpoint, presign_options: -> (request) do
  filename = request.params["filename"]
  {
    content_disposition: "attachment; filename=\"#{filename}\"", # download with original filename
  }
end
```
but after fetching I'm getting this: (shrine-s320180716-13006-qlozpx.xlsx)

```
#<File:/var/folders/cr/dhmpnh2j1nl3wbl5tbwmwrk80000gn/T/shrine-s320180716-13006-qlozpx.xlsx>
```

but it should be actual file name. Though I've used the  plugin in uploader but the result is same.
Please let me know how to solve this.
### System configuration
**Ruby version**:
2.4.2
**Shrine version**:
shrine (2.11.0)

**Comment by janko-m** [comment]
`Shrine::UploadedFile#download` will always download the remote file to a Tempfile with a random filename. A Tempfile needs to be used for this, otherwise there would be a risk of clashing filenames or leaking file descriptors.

If you want to download the remote file to a path with the original filename, you can use `Shrine::UploadedFile#stream`:

```rb
uploaded_file.stream("/path/to/#{uploaded_file.original_filename}")
```
