### ISSUE TITLE
Render image_url to json

### ISSUE THREAD

**Issue by nicksarafa** [shrinerb/shrine#288]
- Issues are for bug reports only.
- Have a question or unsure if it's a bug, then please inquire on the [ruby-shrine Google Group](https://groups.google.com/forum/#!forum/ruby-shrine).
---

### Brief Description
I'd like to save the `image_url` to on upload of the file, or alternatively, render the `image_url` to json without relying on embedded ruby. Any advice on how to do so? I can't seem to find any information on passing the attribute or saving it to the database. I would expect someone has made a `store_image_url` similar to the `store_dimensions` plugin

### System configuration
**Ruby version**:
2.4.1

**Shrine version**:
2.11.0

**Comment by janko-m** [comment]
The file URL isn't your typical metadata, because it cannot be extracted from the IO object, it relies on the storage and the upload location, and since upload location is generated after extracting metadata, it doesn't function on the same principle.

But you can still save it to the metadata after upload, you can use the `hooks` plugin for that:

```rb
Shrine.plugin :hooks

class ImageUploader < Shrine
  def around_store(io, context)
    uploaded_file = super
    uploaded_file.metadata["url"] = uploaded_file.url
    uploaded_file
  end
end
```

Btw, GitHub issues are for bug reports only, usage questions should be asked on the ruby-shrine Google group, as stated in the issue template 😉
