### ISSUE TITLE
Some Images not loading when uploading multiple

### ISSUE THREAD

**Issue by jeremylynch** [shrinerb/shrine#290]
When uploading multiple images (ie > 10) on the [Rails Demo](https://github.com/erikdahlstrand/shrine-rails-example), sometimes the images do not load. See the below video:

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/3665457/45100816-7eb2d180-b16d-11e8-900b-03f581e36a8f.gif)

**Comment by hmistry** [comment]
Thank you for the screenshot. Could you provide us with some more info?
1. Are there any validation failures, errors in logs, timeouts, etc? Both client side and server side.
2. Do you see all the images uploaded in `public/upload/...` folders? There's a cache and store folder.
3. Do you see all the images info recorded in the database?
4. Is the background still resizing the images?
5. Anything else that can helpful to us to debug it?

**Comment by jeremylynch** [comment]
Hi @hmistry thanks for getting back to me. 
1. No validation failures in either the client of server. 
2. Yes all the images are being uploaded to the `uploads/cache` but not anywhere else. 
3. The images are not all being recorded in the database as I cannot save due to validation errors from the blank entries: 
```
Album Name can't be blank
Album Cover photo can't be blank
```
4. No the background does not appear to be resizing them. 

This is easily replicated by running the Rails Demo app.

**Comment by jeremylynch** [comment]
I worked out the issue. When uploading multiple files they are added extremely quickly, and because `Date.now()` is used to generate the `id`, sometimes two of the files have an identical `id`. 
To solve this I added [UUID](https://www.npmjs.com/package/uuid) and am now generating ids using: 
```
uuid.v4()
```

**Comment by hmistry** [comment]
That's great. Would you be able to make a PR with the fix?

**Comment by janko-m** [comment]
@jeremylynch Thanks for the great bug report, and figuring it out 👍

Note that these numbers are not ids, just arbitrary numbers keys required by the ActiveRecord's (and Sequel's) nested attributes feature (the ids are specified by the `_id` field in individual photo attributes).

I first thought that these numbers need to be incrementing in order for nested records to be created in that order, but through testing I found out that regardless of those keys the records will be saved in the same order (the form fields will be submitted in their order, and then since Ruby's Hash is a sorted map, the order will be maintained). So the keys can indeed be strings, in which case your idea of using UUID's sounds like the right way to go 👍

**Comment by janko-m** [comment]
`uuid` seems to be a Node.js feature, I couldn't find it supported natively in client side JavaScript. I chose this instead:

```js
Date.now().toString(36) + Math.random().toString(36).substr(2, 9)
```
