### ISSUE TITLE
[Feature Request] Convenience method for versions

### ISSUE THREAD

**Issue by TrevorHinesley** [shrinerb/shrine#305]
I've noticed that it's possible to have the raw file get attached without versions (so no hash is available on the attachment attribute) if errors happen in the `:store` plugin's block, or if processing is done in the background.

Obviously, we could have boolean columns in the database to signify when processing succeeds or has completed, but `model.attachment_column.respond_to?(:[])` would essentially do the same thing. Would it make sense to have a convenience method around versions? Like `.has_versions?`

**Comment by hmistry** [comment]
Thank you for the request. I think it makes sense and nice to have such a method. In the current implementation, it might be a bit difficult to have a generic test for `has_versions?` because in the processing plugin, one can replace the original with a single "version" file in which case does one treat that as a version or original. Also it depends on how they structured that hash. 

We'll think about it for the current `versions` plugin.

I'm in the process of writing a new versions plugin so I'll be sure to add the method in there.

**Comment by janko-m** [comment]
I'm not sure that adding a `#has_versions?` method would be useful, because it would have to be added on `Shrine::Attacher` (in order to not pollute the model with more methods), so calling it would at the end be longer than just checking whether the returned attachment is a Hash.

```rb
record.attachment.is_a?(Hash)
# vs
record.attachment_attacher.has_versions?
```

**Comment by TrevorHinesley** [comment]
I think that it would make sense as an attachment method. For instance, `record.attachment.has_versions?` is much more indicative of what is being queried, particularly to new devs or those unfamiliar with shrine's DSL. `record.attachment.is_a?(Hash)` is fairly cryptic in that it doesn't directly means "has versions." 

There are probably other considerations here (maybe people use versions differently and checking for a hash wouldn't work in every case, as was hinted by @hmistry), but I think the idea is to have some sort of convention here so the interface is consistent in its use. Just my $.02 though!

**Comment by janko-m** [comment]
@TrevorHinesley This cannot be an "attachment" method, because `record.attachment` will return either a single `Shrine::UploadedFile` object or a hash of `Shrine::UploadedFile` objects. Defining `#has_versions?` method on the result of `record.attachment` would require defining it on `Shrine::UploadedFile` class and on Ruby's `Hash` class, neither of which would make sense. The latter is hopefully obvious, while the former isn't possible, because `Shrine::UploadedFile` represents a single file on storage, and as such has no knowledge of other versions.

With the new derivatives API we are working on ("derivatives" will be a new name for "versions"), derivatives will be accessed separately from the original file (via the new `#attachment_derivates` method), so you would be able to do this:

```rb
record.attachment_derivatives.any?
```

This should be both convenient and intention revealing, so I don't expect we'll need additional methods. Since the `versions` plugin will become deprecated soon after the release of the derivatives API, I don't think it would be worthwhile thinking of additional convenience methods for it. The only option I see is `record.attachment_attacher.has_versions?`, so if you happen to prefer that we could add it.

**Comment by TrevorHinesley** [comment]
@janko-m yep, I didn’t think about attachment just being one of those two object types. You could wrap hash in a Shrine::VersionsHash class, allowing for customization and delegating the rest of the methods to Hash, but I agree that since you’re releasing a new interface for versions, it’s overkill and basically adding to a deprecated DSL.

Thanks a ton for the back and forth! Excited for derivatives.

**Comment by janko-m** [comment]
> You could wrap hash in a Shrine::VersionsHash class, allowing for customization and delegating the rest of the methods to Hash.

That wouldn't work when we have a single file, as in that case we don't return a Hash but a single `Shrine::UploadedFile` object. I agree it's not good to have an inconsistent method return value in the first place, but at least the new derivates API will make it consistent.
