### ISSUE TITLE
[Suggestions needed] Delete unused files from cache

### ISSUE THREAD

**Issue by akhil-gautam** [shrinerb/shrine#306]
I was looking into [Shrine Example](https://github.com/erikdahlstrand/shrine-rails-example), I noticed a behavior that shocked me.
Suppose a user clicks on **Choose Files** and chooses a valid file. The file is then uploaded to the **cache**. But now if the user closes the tab and doesn't submit the form, the file still remains in the cache folder.

Is there any way I can delete those unused files? Deciding which file is unused is what I am not able to understand because the user might think to submit the complete form later(after a couple of hours or even a day later). What should be the best approach to get rid of those unwanted files?

**Comment by jrochkind** [comment]
As mentioned in the Issues template, questions are preferred on the [email list](https://groups.google.com/forum/#!forum/ruby-shrine) instead of here, but I'll answer it anyway!

You are correct what's going on.  The issue is that your software needs a stored copy somewhere before save, so the file can be validated, and/or so it can be preserved if the user does submit the form but there are errors -- whether with the file or other validation errors, you don't want to make the user choose the file again to re-submit after errors. So the file has to be hanging around somewhere. 

You _could_ not store the file on the _server_ until the user presses submit. The particular example you link to sends the file immediately, because that's often a pretty nice user experience. But you could configure your front-end code to not send the file until the user presses submit the first time -- but because of what we discussed in the previous paragraph, that wouldn't really take care of the issue; there would still be cases where there's a file in cache that hasn't actually been saved. 

There are ways to configure shrine to delete the file in cache _when_ it's saved permanently. This is what the [DeletePromoted](https://shrinerb.com/rdoc/classes/Shrine/Plugins/DeletePromoted.html) plugin does. But, again, that **still** would only reduce the problem, because some files might _never_ get actually promoted (permanently saved), a user can simply step away from their browser and never come back, and we have no way to catch that. 

So ultimately, there is no way to avoid _some_ files ending up abandoned in cache. This is actually _exactly_ why shrine makes the distinction between `cache` and `store` -- the files in cache are exactly the ones that are "in process" and may have been abandoned. 

The expectation is that you should set up a regular job to delete old files in cache. You're right that the user could come back to the form a couple hours or even a day later -- it's up to you to decide how long you want to leave the file there in case the user comes back. You can keep them for weeks if you want the user to be able to come back to the form weeks later, and are willing to spend the storage to keep those files around. A day or so is probably more reasonable. 

This is discussed, along with sample code/strategies for handling it, in the README, at: https://github.com/shrinerb/shrine#clearing-cache

**Comment by akhil-gautam** [comment]
Sorry for asking it here. And thanks for this clear explanation. :)

**Comment by twe4ked** [comment]
Updated documentation location: https://shrinerb.com/docs/getting-started#clearing-cache
