### ISSUE TITLE
backgrounding does not respect custom store/cache

### ISSUE THREAD

**Issue by jrochkind** [shrinerb/shrine#310]
I can tell an attachment to use differently registered store/cache storages:

    include ImageUploader::Attachment.new(:image, cache: :custom_key, store: :custom_key)

And it works. 

But if I try to use backgrounding, it doesn't. the promotion fails. If you look at job failure to figure out what the exception was:

```
#<Shrine::Error: storage :cache isn't registered on ImageUploader>
/Users/jrochkind/.gem/ruby/2.5.3/gems/shrine-2.13.0/lib/shrine.rb:142:in `find_storage'
/Users/jrochkind/.gem/ruby/2.5.3/gems/shrine-2.13.0/lib/shrine.rb:210:in `initialize'
/Users/jrochkind/.gem/ruby/2.5.3/gems/shrine-2.13.0/lib/shrine.rb:518:in `new'
/Users/jrochkind/.gem/ruby/2.5.3/gems/shrine-2.13.0/lib/shrine.rb:518:in `initialize'
/Users/jrochkind/.gem/ruby/2.5.3/gems/shrine-2.13.0/lib/shrine/plugins/backgrounding.rb:268:in `new'
/Users/jrochkind/.gem/ruby/2.5.3/gems/shrine-2.13.0/lib/shrine/plugins/backgrounding.rb:268:in `swap'
/Users/jrochkind/.gem/ruby/2.5.3/gems/shrine-2.13.0/lib/shrine.rb:589:in `promote'
/Users/jrochkind/.gem/ruby/2.5.3/gems/shrine-2.13.0/lib/shrine/plugins/backgrounding.rb:152:in `promote'
```

Is there any way to get backgrounding to work with custom storage keys?

**Comment by janko-m** [comment]
Thanks for reporting this, it indeed is a bug. It happens when the record gets reloaded to check whether the attachment has changed before promotion. The issue is that Shrine instantiates a `Shrine::Attacher` instance around the reloaded record directly, it doesn't go through `Shrine::Attachment`, so it doesn't pick up the storages that were configured on the `Shrine::Attachment` level.

I'm not really sure how to fix this. The reason why `Shrine::Attacher` is used directly is to support the case when `Shrine::Attachment` isn't included in the model (e.g. if people don't want pollution or they want to be more explicit). I'm guessing something like this in `Attacher#swap`:

```rb
def swap(new_file)
  if self.class.respond_to?(:find_record)
    reloaded = self.class.find_record(record.class, record.id)
    return if reloaded.nil?

    attacher   = reloaded.send(:"#{name}_attacher") if reloaded.respond_to?(:"#{name}_attacher")
    attacher ||= self.class.new(reloaded, name)

    return if attacher.read != self.read
  end
  super
end
```

If you want to make this patch, feel free, otherwise I will have time on Friday to pick it up.

**Comment by jrochkind** [comment]
sounds like you are pretty sure how to fix it? 

The hard part is figuring out how to write tests, but I'll see what I can do!

**Comment by jrochkind** [comment]
Thanks for pointing out the relevant lines/reason. 

It also occurs to me that for this use in swap, it actually _doesn't matter_ if the attacher knows it's store/cache properly.  

If I just had a `cache` and `store` _registered_, even to things I never planned to use, it wouldn't error and would work fine. But that's a weird workaround. 

I wonder if there's any way for `swap` to do what it needs without actually instantiating an Attacher and making it complain. Probably no great way. Hm. Your fix is prob best, although it's also kinda weird.
