### ISSUE TITLE
Storage Clear does not work corectly on symlinked directories

### ISSUE THREAD

**Issue by jhmegorei** [shrinerb/shrine#334]
Ruby Version: 2.5.1
Shrine Version: 2.12.0

We use `RAILS_ROOT/public/cache/` as Cache directory with the Shrine::Storate::FileSystem class.
The directory is a symlink to a shared directory, so a capistrano deploy does not break a running File conversion raketask.

This creates two separate issues:

1) `Shrine.storages[:cache].clear!` removes the symlink (without touching the original shared directory) and replaces it with a fresh (unsymlinked) cache/ directory.
The new cache directory will be rotated by the capistrano deployment, so it adds to used hard drive storage (temporarily, until the old release is deleted).

2) When I tried `Shrine.storages[:cache].clear!(older_than: 1.hour)`, expecting files older than 1 hour to be removed, it just removed the symlink as well.

# Expected Behaviour
Whether or not clear! should remove and/or recreate symlinks might be topic for debate.

Traversal of the symlinked directory using `clear!(older_than: 1.hour)` should remove the correct files though.

# Code Location and Issue recreation
The code in question is

```
# lib/shrine/storage/file_system.rb
def initialize(directory, prefix: nil, host: nil, clean: true, permissions: 0644, directory_permissions: 0755)
  ...
  if prefix
    @prefix = Pathname(relative(prefix))
    @directory = Pathname(directory).join(@prefix).expand_path
  else
    @directory = Pathname(directory).expand_path
  end
  ...
end
```
and
```
# lib/shrine/storage/file_system.rb
def clear!(older_than: nil)
  if older_than
    directory.find do |path|
      if path.file? && path.mtime < older_than
        path.delete
        clean(path) if clean?
      end
    end
  else
    directory.rmtree
    directory.mkpath
    directory.chmod(directory_permissions) if directory_permissions
  end
end
```

Pathname.expand_path causes the trailing / in the directory definition to disappear, while creating an absolute path.
The result looks like `/var/www/APP_NAME/current/public/cache`.
The missing / at the end causes `directory.find` to malfunction and listing only the symlink, not the directory's content.

Example:
```
irb(main):016:0> Pathname.new('public/cache').find do |path| puts path end
public/cache
=> nil

irb(main):017:0> Pathname.new('public/cache/').find do |path| puts path end
public/cache/
public/cache/0021ddaefe8f1bda1dd7101492658bd4.jpg
public/cache/00329f41c8677c8927d9d6948f407096.jpg
...
```

A simple fix would be using `Pathname.realdirpath` instead of `Pathname.expand_path` in the initializer. It correctly resolves the symlink and lists the directory's contents for both `public/cache` and `public/cache/`.

**Comment by janko-m** [comment]
Thanks for the detailed report and coming up with a solution!

I think `Pathname#realdirpath` is probably what we're looking for, but I think it would be better for it to be called dynamically in `#clear!` rather than on initialization. That way `Shrine::Storage::FileSystem` methods like `#directory` and `#path` will still return symlinked paths, which I think is desirable.

For `#clear!` with argument we also need to make sure the actual directory is not deleted. Currently it's deleted and re-created, which is not ideal.

**Comment by janko-m** [comment]
I pushed a [fix](https://github.com/shrinerb/shrine/commit/306f9a45f2fd74c8d342ef7d0646d7ff3f50bf3d), please let me know if it works for you. The next release should be coming up this week.

The only thing I'm confused about is that you said `FileSystem#clear!` with the `:older_than` argument was deleting the symlink. That should not happen, because Shrine checks whether `Pathname#file?` is true before it deletes, and for symlinks `Pathname#file?` return `false` (whereas `Pathname#symlink?` returns `true`). So I just want to understand if on your filesystem `Pathname#file?` return `true` for symlinks. I only tested on Mac OS Mojave.

**Comment by jhmegorei** [comment]
You're right, I may have mixed that up during my experiments. The directory is not deleted but simply ignored in that case (as find only finds the symlink and does nothing as it is not a file).

I'll try the fix :)

**Comment by jhmegorei** [comment]
The fix worked fine. The symlink remained but the directory was cleared out correctly.
