### ISSUE TITLE
IO.copy_stream TypeError

### ISSUE THREAD

**Issue by speedo-spin** [shrinerb/shrine#353]
trying to upload file according to the doc (file storage), but getting this error when calling `update(params)` on instance

```
TypeError (can't convert ActionDispatch::Http::UploadedFile to IO (ActionDispatch::Http::UploadedFile#to_io gives Tempfile)):
```

seems like it fails here https://github.com/shrinerb/shrine/blob/master/lib/shrine/storage/file_system.rb#L54

rails 6 beta
ruby 2.6.1

**Comment by speedo-spin** [comment]
yeah, if I pass io.to_io `bytes_copied = IO.copy_stream(io.to_io, path!(id))`
then it works

**Comment by janko** [comment]
Thanks for the report. It appears that this was working prior to Ruby 2.6, but version 2.6.0 changed the behaviour of `IO.copy_stream` in a way that's not backwards compatible. I will investigate this further.

The workaround you posted is ok, though I think it would be better to create a subclass of the `FileSystem` storage, as its public interface is stable and it's where the problem happens.

```rb
class FileSystem < Shrine::Storage::FileSystem
  def upload(io, id, **options)
    io = io.to_io if io.is_a?(ActionDispatch::Http::UploadedFile)
    super(io, id, **options)
  end
end

Shrine.storages = {
  cache: FileSystem.new(...),
  store: FileSystem.new(...),
}
```

**Comment by janko** [comment]
It wasn't a change in Ruby. Rails 6 added [`ActionDispatch::Http::UploadedFile#to_path` ](https://github.com/rails/rails/pull/28676), which changes the behaviour of `IO.copy_stream`, where if the object responds to `#to_path`, it tries to call `#to_io` and expects an instance of `IO` class back (`File` is one, but `Tempfile` is not).

**Comment by jrochkind** [comment]
interesting. I wonder what the solution is. I guess here is where duck-typing goes wrong, you can check `respond_to?(:#to_io)`, but that doesn't mean what's returned will be what you expect. 

I wonder what we can do to be safer overall for future/unknown objects, not assuming that just because they have a `to_path` that means a certain thing. Is it being too generous checking for duck-type `#to_path` as a proxy for `File`, should it just be checking `kind_of? File`?

(as a side issue, i think it's probably a bug in ruby that Tempfile isn't an `IO`, or actually a subclass of `File`, but it's what we got).

**Comment by janko** [comment]
Just to clarify, this is all in `IO.copy_stream` method itself. It has a `if source.respond_to?(:to_path)` conditional somewhere in it, inside which it will call `source.to_io` and expect it to return a subclass of `IO` (that's all C code). I wasn't even aware of this behaviour until I tested each `ActionDispatch::Http::UploadedFile` method and saw that `#to_path` was the one that breaks `IO.copy_stream`.

Considering that it would be nice if `ActionDispatch::Http::UploadedFile` was compatible with `IO.copy_stream` in general, it would be best to push the fix to Rails. I already know the fix – instead of `ActionDispatch::Http::UploadedFile#to_io` returning `Tempfile`, we make it return a `File` object by calling `#to_io` on the `Tempfile`.

This might be slightly backwards incompatible if someone was calling `#to_io` and expecting to get an actual `Tempfile` object, but luckily Rails 6.0 will be a major release, so it's ok. I'll go ahead an make the PR.

**Comment by jrochkind** [comment]
If you can get that in Rails before 6.0.0, that'd be great, I wonder how controversial it will be though. We'll see, thanks @janko !

I do still wonder if assuming that _anything_ that has a `to_path` will also have a `to_io`, and that `to_io` will _necessarily_ return something that subclasses `IO` (or is otherwise IO-like to shrine)... is really a safe future-proof assumption. We can (maybe) change the particular relevant Rails class to satisfy this assumption, but is that really a safe "duck-typing" assumption, or could other things in the future be likely to break it too?

**Comment by jrochkind** [comment]
That is, if `respond_to?(:to_path)` was _really_ just a proxy for "is it a `File`?", but we were hoping to be more flexible/duck-typing to allow other things too... maybe that was _too much_ flexibility, and the guard should just be `if thing.kind_of?(File)` instead of `if thing.respond_to?(:to_path)`?

**Comment by janko** [comment]
> I do still wonder if assuming that _anything_ that has a `to_path` will also have a `to_io`

I just checked, and `IO.copy_stream` only calls `#to_io` if it's defined.

> maybe that was actually _too much_ flexibility, and the guard should just be `if thing.kind_of?(File)` instead of `if thing.respond_to?(:to_path)`?

I'm guessing that `IO.copy_stream` does this whole dance to achieve some performance optimization. If the conditional was `if thing.kind_of?(File)`, then it wouldn't hold true for `Tempfile`, so a `Tempfile` source wouldn't get that performance optimization.

Moreover, `if thing.respond_to?(:to_path)` also covers `Pathname`, so I guess it's nice to have a single conditional for both. But it's complex C code that I haven't read, so who knows what is the actual logic 🤷‍♂️

> We can (maybe) change the particular relevant Rails class to satisfy this assumption, but is that really a safe "duck-typing" assumption, or could other things in the future be likely to break it too?

Honestly, I'm not worried about potential breakage. I think it's really rare the user will upload something that's not a Ruby IO (`File`, `Tempfile`, `StringIO`) or a Shrine IO (`Down::ChunkedIO`, `Shrine::Plugins::RackFile::UploadedFile`, `Shrine::Plugins::DataUri::DataFile`), and probably even rarer that this IO object will define `#to_path` *and* `#to_io` where `#to_io` doesn't return an actual `IO` object.

Even if there was a real chance, I'm not sure what I would suggest to the Ruby core team; the current behaviour seems reasonable to me.

**Comment by janko** [comment]
PR https://github.com/rails/rails/pull/35382 has been merged, so it should be part of the next Rails 6.0 beta/release candidate. After that the mentioned workaround won't be needed anymore.

**Comment by jrochkind** [comment]
Oh I'm sorry, I missed that it was in stdlib `IO#copy_stream`, not shrine code. I get it now!
