### ISSUE TITLE
No way to disable Marcel MIME type fallback

### ISSUE THREAD

**Issue by aried3r** [shrinerb/shrine#354]
### Brief Description
After https://github.com/shrinerb/shrine/commit/b1e5d8362a8204e287d1609b580ccb90f8f009d6 Marcel will fall back to the file extension if it can't determine the MIME type.

In combination with the `infer_extension` plugin this will result in a random binary file with the wrong extension (i.e. `not-really-a-jpg.jpg`) getting the `.jpeg` extension instead of `.bin` like it would have before this commit.

There's a way to define multiple analyzers using something like

```Ruby
plugin :determine_mime_type, analyzer: -> (io, analyzers) do
  mime_type = analyzers[:file].call(io)
  mime_type = analyzers[:mime_types].call(io) if mime_type == "text/plain"
  mime_type
end
```

but I want to rely on Marcel first and foremost and now I'd have to use multiple analyzers just in case Marcel gets fooled by the extension.

### Expected behavior
Using the `infer_extension` plugin a binary file should get the appropriate `.bin` extension, even if it has a name ending in something else during upload, like `.jpg` (sic! `.jpg` results in `.jpeg` after Marcel and infer_extension, as is expected).

### Actual behavior
Marcel reports a `image/jpeg` MIME type and thus `infer_extension` reports a `.jpeg` extension.

### Simplest self-contained example code to demonstrate issue
I'll see if I can mock up a failing test case, what I was able to do to reproduce this issue is doing something like this in tests:

```Ruby
fakeio('a' * 100, filename: 'not-a-jpeg.jpg')
```

### System configuration
**Ruby version**: 2.6.1

**Shrine version**: 2.16.0

**Comment by jrochkind** [comment]
I had this same thought about marcel -- I think when I was worried about it, the shrine/marcel configuration _wasn't_ using fallbacks, but I think it was since "enhanced" to use them. 

I agree there should be a way to configure shrine with marcel as a mime determiner, but tell it _not_ to use any user-agent supplied metadata -- for another reason, because you might simply not want to trust it.

**Comment by jrochkind** [comment]
@aried3r It might be worth bringing this up with `marcel` on their GH issues, as this is kind of the way marcel works. But we're considering adding a setting to tell shrine not to share user-agent-supplied filename or mime-type at all, even though that's not quite how marcel wants to be used. 

You could also consider using the `mimemagic` analyzer instead of `marcel`. Marcel actually uses mimemagic under the hood, although it supplies it's own additional logic (such as using user-agent supplied metadata), and has it's own definition file which may not match mimemagic's (which may make it undesirable, I understand)

**Comment by aried3r** [comment]
Thanks for your input. I'll try out `mimemagick` and maybe open an issue with `marcel`. I'm not quite sure how to phrase it, since – as you mentioned – it's the way it wants to be used.

**Comment by hmistry** [comment]
Hi @aried3r. Thanks for the issue. We've been discussing it amongst the team and investigating Marcel and the edge cases. It's really a tough one, on the one hand certain files like `.xls` need the filename to get the right mime type like that commit message says, but on the other hand, we may not want to trust the filename at all for security reasons or in your case, it's giving a wrong type.

Marcel way of disabling fallbacks is to not provide a filename, extension, and content type and so if any one of those are present, they assume the user intends to use that as a fallback. Marcel uses the filename to handle cases like `.xls` to get the right mime type.

So for Shrine, we now need to consider all this and will decide shortly how we wish to proceed. Most likely will be some form of an option like what @jrochkind mentioned above.

**Comment by jrochkind** [comment]
@aried3r perhaps on the marcel issue, point out the problem you are having with a random binary file being determined to be a jpg based on filename.  Without needing to bring shrine into it. There are potential security implications to this -- there have been vulnerabilities before related to something being processed as a content-type it isn't really, and which haven't been verified with magic bytes. See https://imagetragick.com/  There can be such vulnerabilities again, which is a main reason why we do magic-byte analysis in the first place, instead of just using the filename suffix, which is of course what marcel is for!

I'm not totally sure how much response you're going to to get on marcel, it's not clear how much maintanance it's getting. But seems worth filing, since this is really a marcel issue, although possibly shrine can help work around it.

**Comment by hmistry** [comment]
@aried3r PR #356 has been merged into master. Marcel no longer uses filenames as a fallback by default. The user can opt-in to using filename as fallback by passing in analyzer options to the `determine_mime_type` plugin when using Marcel as the analyzer.

I'm going to close this issue as the PR addresses it.

**Comment by jrochkind** [comment]
We should be aware we had one(?) release in the major release series, until the next release, where marcel _did_ use filenames, but the ones on either side didn't. If anyone reports an issue with marcel analyzer later.

**Comment by aried3r** [comment]
Thank you, the change looks great!
