### ISSUE TITLE
After promote or swap hook

### ISSUE THREAD

**Issue by legendetm** [shrinerb/shrine#389]
### Brief Description
I'm using Shrine with background promote worker and I need to call other worker when uploaded file is successfully promoted to store.

At first I tried to use `hooks` plugin `after_upload` to kick off Sidekiq worker, but it generates race condition, because the file is actually swapped after `after_upload` hook.

```ruby
plugin :hooks

def after_upload(io, context)
  super
  process_payment_file(context[:record]) if context[:phase] == :store
end  

def process_payment_file(payment_file)
  ProcessPaymentFileWorker.perform_async(payment_file.id)
end
```

Sidekiq log
``` 
ShrinePromoteWorker INFO: start
ProcessPaymentFileWorker INFO: start
ShrineDeleteWorker INFO: start
ShrinePromoteWorker INFO: done
ShrineDeleteWorker INFO: done
ProcessPaymentFileWorker INFO: fail - Aws::S3::Errors::NotFound
```

### Expected behavior
I expect Shrine to have a hook or method to that is called after promote - after the file is uploaded and the activerecord is updated

### Actual behavior
Didn't find a way to call other worker after successful store promote.

### System configuration
**Ruby version**: 2.5.5

**Shrine version**: 2.17.1

**Comment by jrochkind** [comment]
I've ended up custom-hacking this into my uploader (which is customized enough in various ways that I'm not sure if my code is helpful). 

I've thought before that we should have a hooks-type plugin that does not require you to call `super` (which is easy to forget, and in my opinion leads to hard to debug code), but uses block style `after_upload { some stuff }` or `after :upload { some stuff }`, and supports "promotion" as a concept for before or after.

**Comment by legendetm** [comment]
After writing the issue, I found a workaround 
```ruby
plugin :hooks

def after_upload(io, context)
  super
  process_payment_file(context[:record]) if context[:phase] == :store
end

def process_payment_file(payment_file)
  payment_file.singleton_class.after_commit do
    ProcessPaymentFileWorker.perform_async(payment_file.id)
  end
end
```

**Comment by janko** [comment]
I will take this feature request into consideration. I'm currently rewriting `Shrine::Attacher` on order to fix some design decisions, and I will think about the possibility of adding these hooks.

Since the current `hooks` plugin operates on the **uploader** level, and these hooks will operate on the **attacher** level, I agree with Jonathan that we'll definitely want to switch to a block-based API.

**Comment by janko** [comment]
In Shrine 3.0 (which will be the next version after 2.19.0), promotion will be separate from persistence. In other words, the `Attacher#promote` method will always only upload the cached file to permanent storage, regardless of whether the `activerecord` plugin is loaded or not. Moreover, the persistence after promotion will be different when it's synchronous vs when it's in a background job (a different method is called).

This makes it a difficult to make a promotion hook that works as mentioned here – execute after persistence, in both synchronous and backgrounding approaches. The approach you have above is very brittle, because in the `after_upload` hook you're not inside any transaction, so I'm guessing `after_commit` hook is registered for the *next* transaction.

Since callbacks are bad in general, I'm incline to say that Shrine won't come with an after-promote hook; in Shrine 3.0 the `hooks` plugin will get deprecated as well. The user will simply have to execute that code directly, in your case I believe you're better off creating a hook on the *ActiveRecord* level rather than Shrine level (because really it's related to the `PaymentFile` model rather than the uploader):

```rb
class PaymentFile < ActiveRecord::Base
  include Shrine::Attachment[:file]
  # ...
  after_commit on: :update do
    if file_data_previously_changed? && file_attacher.stored?
      ProcessPaymentFileWorker.perform_async(id)
    end
  end
end
```

In my opinion it's best not to use callbacks altogether:

* without backgrounding:

  ```rb
  payment_file = PaymentFile.create(payment_file_params)

  if payment_file.file_attacher.changed?
    ProcessPaymentFileWorker.perform_async(id)
  end
  ```

* with backgrounding:

  ```rb
  class Attachment::PromoteJob
    def params(data)
      attacher = Shrine::Attacher.promote(data)

      if attacher && attacher.record.is_a?(PaymentFile)
        ProcessPaymentFileWorker.perform_async(payment_file.id)
      end
    end
  end
  ```

So for now I'm closing this issue.

**Comment by jrochkind** [comment]
Hm, I don't personally view callbacks as bad in general. In my current use of Shrine 2, I have engineered a way to have an after promote callback myself, and it has been useful to me. 

I guess I'll wait and see if I can work out a way to do it in shrine 3!

**Comment by Aryk** [comment]
> Hm, I don't personally view callbacks as bad in general. In my current use of Shrine 2, I have engineered a way to have an after promote callback myself, and it has been useful to me.
> 
> There are all sorts of things you might want to do only when a file has been successfully promoted to `store`, because that's when it's really ready for public access.
> 
> I guess I'll wait and see if I can work out a way to do it in shrine 3!

Curious, did you find a way to do it in Shrine 3? I'm having the same issue.

**Comment by jrochkind** [comment]
@Aryk I did implement that, with some code I'm not super happy with, but it totally works. 

I'm not totally happy with my code, some of my own custom logic ended up interspersed with it. Plus I put the after/before/around_promotion callbacks on teh *model*. 

My models have only ONE shrine attachment in them, so this works -- but I think it would be a better design to have it on the uploader, but my code just ended up this way, and it was good enough so I didn't spend more time making it better. 

A shrine plugin https://github.com/sciencehistory/kithe/blob/master/lib/shrine/plugins/kithe_promotion_callbacks.rb

That plugin depends on another custom plugin... it gets kind of interspersed with logic I wrote to let you turn on/off these callbacks and other stuff... you might not be able to use my code as-is, but maybe it will give you a clue. 

Then in your model you just do: `define_model_callbacks :promotion`, and you can define `after_promotion`, `before_promotion`, `around_promotion` in it.
