### ISSUE TITLE
Support for Dynamic Scoping of Location

### ISSUE THREAD

**Issue by esb** [shrinerb/shrine#396]
Currently it's possible to scope files by generating the location with some custom code.

For example, one can upload a file to "/users/:user_id/photos/12345.jpg".

This is all fine and well, but the scoped id is fixed, once it's been stored. In the above example, if we have a storage at "/users", then the uploaded image would have an id of "543/photos/12345.jpg" for user 543. The problem comes when you want to backup/restore or migrate the data associated with user 543 to a different user. In order to do this, all the photo records for the new user must be hacked to change the ids from "543/photos/12345.jpg" to, say "987/photos/12345.jpg".

It might be a nice idea if there was some way of specifying a model specific prefix that could be appended to all records to allow for dynamic scoping. For example, the photo ids could just be the bare image name, "12345.jpg". The model specific prefix could be "#{self.user_id}/photos", so that a dynamic location would be generated based on the actual photo record that the file is attached to. This could be declared as an option on the Attachment include for the model.

Does this idea have any merit?

**Comment by janko** [comment]
You should be able to achieve this with the combination of `default_storage` and `dynamic_storage` plugins:

```rb
plugin :default_storage, store: -> (record, name) {
  :store_#{record.class.table_name}_#{record.id}_#{name.pluralize}" # e.g. :store_users_543_photos
} 

plugin :dynamic_storage
storage /store_([[:alpha:]]+)_([[:alpha:]]+)_([[:alpha:]]+)/ do |match|
  Shrine::Storage::S3.new(
    prefix: match.captures.join("/"),
    **s3_options
  )
end
```

The `default_storage` sets the storage name depending on the record and attachment name, while the `dynamic_storage` resolves these storages into specific instances. I haven't tested this code, but something like that should work.

If you have problems implementing this, you can ask further questions on the `ruby-shrine` google group, which is intended for usage questions. GitHub issues are only intended for bug reports and important feature requests.

**Comment by esb** [comment]
Hi Janko,

I had a look at your proposed solution, but it creates essentially the same problem that I'm trying to solve.

The dynamic part of this is done at the time of uploading, not the time of execution! The dynamic storage solution just stores the hard-coded storage bucket in the record, so nothing changes.

As per the example I gave, I want to migrate or backup and restore records (and associated image files) to a different user. Thus if I upload an image for user 10 it gets stored in bucket "/users/10". Fine. The record and image file then get backed up/restored to a new user (50), and the image is stored in bucket "/users/50" now. It's no use if the dynamic storage field is set to "store_users_10" in the record. This is why I am looking for some way of resolving the bucket path when I access the url for the image based on the actual record at load time, not when the image was uploaded in the first place.

I hope I've explained myself clearly. As I said before, I'm hoping not to have to mangle all the shrine data in the record, once when I back up the records to put in a symbolic placeholder, and then again on restore to substitute the new user id.

**Comment by jrochkind** [comment]
When you say "bucket" "/users/50", I think you're really talking about the _prefix_ in the storage configuration. 

Is there a reason you need to do this using separated Shrine::Storage classes with separate prefixes?

In the "ordinary" way shrine works, the actual current path in the storage is stored in the attributes itself -- it is calculated at storage time, then the actual string is persisted. 

So if you had all users sharing the same bucket/Shrine Storage, but simply had the _path_ (ie, first part of "key") calculated to "/users/50/", then that would be persisted in the model. 

If the user ID changed, you could actually delete/re-upload/move the files through shrine -- and it would be stored in the newly calculated (now different) place. 

If you had some "offline" process moving (backup/restoring) the files to a different location -- you'd just have to edit your database to update the shrine `key` to the new location. 

It might still be a bit confusing to figure out the right ways to do all this. 

But by trying to use "dynamic storage", we introduce a whole additional level of complexity. Are you sure you need it?

If you do, it's possible it can still be worked out. Because one thing I think you are confused about is: 

> The dynamic storage solution just stores the hard-coded storage bucket in the record, so nothing changes.

I don't believe it does. I dont' think the dynamic storage solution stores the hard-coded storage bucket in the record.  *Unlike* the `id`, which is stored in the record, the dynamic storage solution actually is truly dynamic, not stored anywhere, everytime the record is loaded it will be dynamically calculated. 

If you create new record with with a new id -- it will be looking for the files at wherever dynamic storage tells it to. If the files are there -- because you moved or backup/restored them there -- that should be great and all should be well. 

I think it's possible the dynamic storage solution will already do what you need; have you tried it out? Trying it out might help you understand the possibilities, even if it doesn't work. 

I also could be misunderstanding what you want, this stuff is confusing to talk about.

**Comment by janko** [comment]
@esb Oh, right, I understand what you're saying, I apologize for misleading you.

@jrochkind The `dynamic_storage` approach is not really dynamic, because the generated storage identifier would still be persisted in the attachment column, e.g:

```rb
{
  "id": "dsauao89fa.jpg",
  "storage": "store_users_123_photos",
  "metadata": {...}
}
```

So you'd still have the same problem, just with a more complex implementation 😛

@esb The problem with your request is that it's orthogonal to Shrine's philosophy. Coming from Paperclip & CarrierWave, it was not nice that I could change the value of a column, and suddenly all my attachment links are now broken, because the attachment URL was being generated from these columns dynamically.

That's why in Shrine I decided that the location of uploaded files will be generated only on upload, and then persisted in the record. That way the URL will stay the same regardless of what you change, so there is no risk of broken links (unless you explicitly move the files).

I strongly believe that what you want is not a safe approach. Some comments:

1️⃣If your data restore mechanism is not able to retain the original primary key values, then how are your foreign keys still working?
2️⃣I think it's a _good_ thing that Shrine retains the original URLs, because then your data restore isn't dependent on whether you've copied files to a new location; URLs will still continue to work, and you can decide to move your files later (maybe you decide it's not even worth moving the files).
3️⃣The fact that Shrine hardcodes file locations in the column allows you to safely move your files in a separate step.

**Comment by esb** [comment]
Backups are done now by mapping foreign keys in database records to a relative key. This is simple enough, although a little tedious. Uploaded files are just stored with file names as is.

If we upload using Shrine as is, then we end up with foreign keys encoded in the Shrine column data, and at worst, also encoded in the uploaded file names. This means that the backup and restore process must also map the Shrine data to the new foreign keys, and whichever way you look at it, this is somewhat harder to do than simply mapping database fields. You will need to parse out the file locations in the hash and rebuild the data. Of course, it's doable, but feels a bit hacky.

It turns out that I can implement a run-time dynamic file location with only a few simple code patches.

1. Allow for optional options to be passed to the initialize method.

```ruby
class Shrine
   module InstanceMethods
    # Accepts a storage symbol registered in `Shrine.storages`.
    #
    #     Shrine.new(:store)
    def initialize(storage_key, opts = {}) # <== ADD OPTIONS
      @storage = self.class.find_storage(storage_key, opts)
      @storage_key = storage_key.to_sym
    end
  end
end
```
2. Pass the record as an option when creating the Attacher.

```ruby
class Shrine
  class Attacher
    module InstanceMethods
      # Initializes the necessary attributes.
      def initialize(record, name, cache: :cache, store: :store)
        @cache   = shrine_class.new(cache, record: record) # <== PASS RECORD
        @store   = shrine_class.new(store, record: record) # <== PASS RECORD
        @context = { record: record, name: name }
        @errors  = []
      end 
    end
  end
end
```
3. Allow for a Shrine storage to be called if it's a proc.

```ruby
class Shrine
  module ClassMethods
    # Retrieves the storage under the given identifier (can be a Symbol or
    # a String), raising Shrine::Error if the storage is missing.
    def find_storage(name, opts = {}) 
      store = storages[name.to_sym] || storages[name.to_s] or fail Error, "storage #{name.inspect} isn't registered on #{self}"
      store = store.call(opts[:record]) if store.respond_to?(:call)
      store
    end      
  end
end
```
4. Now simply define a Shrine storage with callable code.

```ruby
Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new('users/cache'), # Temporary
  store: Shrine::Storage::FileSystem.new('users'),
  users: -> (record) {
    if record.present?
      Shrine::Storage::FileSystem.new("users/#{record.user_id}/assets/#{record.imageable_type.tableize}")
    else
      Shrine::Storage::FileSystem.new('users')
    end
  }
}
```
