### ISSUE TITLE
"after_commit on: :destory" is different than "after_destroy" and shrine should use after_destroy

### ISSUE THREAD

**Issue by thebravoman** [shrinerb/shrine#488]
### Brief Description
Shrine uses after_commit on: :destroy to call an active_record_destroy callback, but it should use after_destroy.
I use acts_as_paranoid for this object. When there record is fully destroy the record receives and after_destroy callback, but it does not receive an after_commit on: :destory

Looking at:
```ruby

class ContentPicture < ApplicationRecord
  include ImageUploader::Attachment(:image) # adds an `image` virtual attribute 
  after_destroy
    # this gets called TWO times
   puts "from pure active record callback"
  end
end

class ImageUploader < Shrine

  class Attacher < Shrine::Attacher
    def activerecord_after_destroy
      # this gets called ONE time
    end
  end
end

# shrine-3.2.1/lib/shrine/plugins/activerecord.rb
            model.after_commit on: :destroy do
              # This gets called on the first destroy of the record. 
              puts "From shrine callback" 
              if send(:"#{name}_attacher").attached?
                send(:"#{name}_attacher").send(:activerecord_after_destroy)
              end
            end
```

If the calls are 
```ruby
content_picture = ...
content_picture.destroy
content_picture.destroy
```

the output would be
```
from pure active record callback
from shrine callback
from pure active record callback
```

### Expected behavior

There should be two calls of the shrine callback. It should register on after_destroy not on after_commit on: :destroy

### Actual behavior
The callback is received only the first time. 

### Simplest self-contained example code to demonstrate issue
Above

### System configuration
**Ruby version**: 2.6.5

**Shrine version**: 3.2.1

**Comment by jrochkind** [comment]
I think the problem with after_destroy is that it is triggered *before* the database commits. This means the change may not yet be seen by other processes querying the database; it also means the change could be rolled back, and never actually commited. Since shrine deletes the attachment in this hook, that would mean it might delete the attachment prematurely, or even delete the attachment when the record never ends up destroyed in the database at all, which would be bad. For shrine's logic to work as expected here, it really does need to be triggered after a commit. 

Normally this works. You mention `acts_as_paranoid` as if that could be involved? Does that gem somehow change things so the after_commit on destroy  is never called?  

You can perhaps get this to do what you want locally, by just registering the `after_destroy` yourself?  I think it won't work reliably for the reasons mentioned above, but you should be able to do it locally if you want. Or, with more understanding of how `acts_as_paranoid` works, maybe figure out how to make it work reliably without conflicting with that gem. You can even tell the shrine `activerecord` plugin not to register callbacks at all, if you'd prefer to handle that entirely yourself; although it sounds like in this case the existing callbacks aren't hurting, you just need to trigger destroy callbacks in some additional circumstances somehow.

**Comment by thebravoman** [comment]
Thanks. Would look at it.

Have you thought about a transaction logic for deleting the file. Because
if the transaction passes the file could still return an error that it is
not deleted and stay as on the storage as not connected to anything?

**Comment by jrochkind** [comment]
I have thought about it! There isn't any great obvious (to me) solution to tying an action outside of the database (deleting a file) to an rdbms transaction. But shrine does a pretty good already, of avoiding inconsistencies or orphaned files, I'm not sure there's any way to do it better than shrine does, not that I've thought of anyway. 

Note: I have a few commits in shrine, but am not one of the main maintainers myself.

**Comment by thebravoman** [comment]
Thanks. For completeness I also found an issue on acts_as_paranoid and linked it here - https://github.com/rubysherpas/paranoia/issues/337. 

For future references and if anybody is search:
I will try  to use keep_files and will not delete the files in the activerecord,shrine,acts_as_paranoid callback flow. After the file is destroyed, fully, in the after_destroy I will create an background job that would run in a few minutes and delete this file. It will retry three time and it will attach to the already established way of reporting failed jobs that we have. 

If the after_destroy is rollback since it is in a transaction the job will not be created so we are good.

**Comment by janko** [comment]
As @jrochkind explained, Shrine *should* be deleting the files after the transaction commits, because (a) the transaction that destroys the record could be rolled back, (b) someone can fetch the record after the attached file has been deleted but before the transaction has been committed, and (c) we don't want the transaction to have to remain open while the file is deleting (in the synchronous case).

If the destroy `after_commit` callback is not being called with `acts_as_paranoid`, then that's a bug in `acts_as_paranoid`. Or it's a bug in Active Record, which would not be surprising at all, considering that [Active Record's implementation of transaction callbacks is very complex](https://janko.io/the-complexity-of-activerecord-transactions/). In either case, Shrine generally shouldn't have to work around issues in other gems.

**Comment by jrochkind** [comment]
I would now actually say it may be *desired* behavior. 

The point of acts_as_paranoid is keeping old versions around, not *really* destroying them, so you can look at past state, or roll back to past version. 

Do you consider the attached file part of the state you should be able to look at? If you roll back to past version, should it have it's attachment there too, in the restored version?

Present behavior makes both of those things work. I think it's just as likely someone would consider it a problem if it didn't. 

We ought to try to make it easy for you to add your own logic to make this work how you want, but I don't see how it's possible for there to be default behavior that satisfies everyone, and the current behavior actually seems the safest default to me. 

If you really do want to delete attachments in storage for models that have been sort-of destroyed but acts_as_paranoid has kept around -- you should be able to do that with a custom callback you add yourself. You *could* add the `after_destroy` you suggest above yourself on your models -- I would not recommend that for reasons explained above, but you could also add more complex logic in an `after_commit, on: :update` callback that looks at state to confirm that the instance is now acts_as_paranoid pseudo-deleted.

**Comment by thebravoman** [comment]
Thanks guys. I managed to work it out. I have implemented the case as a custom logic on our side so it's all good
