### ISSUE TITLE
Preprocessing file (not derivatives) on attach?

### ISSUE THREAD

**Issue by Aryk** [shrinerb/shrine#502]
I'm on the newest version of Shrine 3.2.1, and I read through this:

https://github.com/shrinerb/shrine/blob/master/doc/processing.md

However, let's say I want to do some things to the original file before it gets attached to Shrine, analyzed etc.

For images, this could be to run auto_orient. For a video, it could be to convert it to mp4. To be clear, I want to overwrite the original file and not make derivatives.

I could not find a plugin or a "best practice" around this in the documentation.

My best guess right now is to override this method

```ruby
   def attach(io, storage: store_key, **options)
        file = upload(io, storage, **options) if io

        change(file)
      end
```

I was looking into #assign method, but the :data_uri plugin completely bypasses that method. #attach is the only thing that always gets called. I want to be able to do:

model.image = file
model.image_data_uri = "base64 string"

And in both cases, it will run an auto_orient on the file to make sure it's the right way...this will propagate to the derivatives naturally of course.

Is this the best way?

**Comment by janko** [comment]
I officially recommend that people always keep the original file, because you never know if you will need it for later processing or reprocessing. By replacing the original file you're losing information; it's the equivalent of keeping only a lossy compressed version of an original image.

However, if you do still want to store only the processed file, overriding `Attacher#attach` would be the right way to go IMO. Or you could create a service object for attaching that does the processing beforehand, which would for me be cleaner than overriding Shrine.

I will close this now, as usage questions should generally be asked on the [Discourse channel](https://discourse.shrinerb.com/).
