### ISSUE TITLE
Resize original file

### ISSUE THREAD

**Issue by Pingou** [shrinerb/shrine#675]
Is there any way to resize the original file? I want to save as much space as possible.
I stumbled on this discussion but it doesn't seem implemented still: https://stackoverflow.com/questions/59021782/how-to-upload-while-resizing-the-original-image-itself-in-shrine

**Comment by hms** [comment]
I have the slightly different problem, but I believe my solution would work for you as well.

You can inject you application requirements into the Shrine's promotion process (Shrine makes it easy and the doc's are pretty clear about how do it).  Instead of simply copying/moving the cached file, you can compress / transform there and make the results available as the stored result and referenced as the promoted resource.

I'm using Minio for development and AWS for production, and it's about 30 lines of code, between having the flexibility of running ImageMagic / Vips for transcoding locally, supporting AWS MediaConvert to transcoding in the the cloud, and my Apps requirements for capturing and storing media metadata as part of Shrines metadata.  If I knew more of your requirements, I could tell if sharing my implementation would help you either as a solution or as an example directionally.

Yet another example excellence the Shrine design and architecture (Big thanks to @janko for the Shrine code *AND* all of his help over the years).

**Comment by Pingou** [comment]
Thank you @hms 
I see that process gives an io argument, can I delete the file with that?

**Comment by hms** [comment]
@Pingou I would stick with the API's for deleting just in case you switch storage infrastructure one day.

**Comment by janko** [comment]
There isn't any official way to process the original in Shrine, you have to do it manually, probably before attaching the file. ImageProcessing gem isn't in any way tied to Shrine, so you can use it the same way.

There used to be a [processing](https://shrinerb.com/docs/plugins/processing) plugin, but it's been deprecated in Shrine 3. You can still use it though if you really need to, it will just issue a deprecation warning.
